import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {demoScore,validateScore,timeline} from '../docs/core.js';
import {encodeWav} from '../docs/audio.js';
const docs=new URL('../docs/',import.meta.url),tracksDir=new URL('tracks/',docs);
await mkdir(tracksDir,{recursive:true});
if(process.argv.includes('--seed'))for(const id of ['joy','scale']){const file=new URL(`${id}.piano.json`,tracksDir);try{await readFile(file);}catch{await writeFile(file,JSON.stringify(demoScore(id),null,2)+'\n');}}
const catalog=[];
for(const file of (await readdir(tracksDir)).filter(f=>f.endsWith('.piano.json')).sort()){
 const raw=await readFile(new URL(file,tracksDir)),score=validateScore(JSON.parse(raw));
 catalog.push({id:score.id,title:score.title,composer:score.composer,tempo:score.tempo,measures:score.measures.length,bytes:raw.length,file:`./tracks/${file}`,revision:createHash('sha256').update(raw).digest('hex').slice(0,12)});
 if(process.argv.includes('--audio')){
  const t=timeline(score),sr=22050,seconds=t.total*60/score.tempo+.5;if(seconds>600)throw Error(`${file}: audio exceeds 10 minutes`);
  const samples=new Float32Array(Math.ceil(seconds*sr));
  for(const n of t.events){const start=Math.round(n.start*60/score.tempo*sr),duration=n.duration*60/score.tempo*.93,hz=440*2**((n.midi-69)/12),velocity=n.velocity??.65;
   for(let i=0;i<Math.ceil((duration+.22)*sr)&&start+i<samples.length;i++){const time=i/sr,attack=.004,decay=Math.min(.18,duration*.45);let env;if(time<attack)env=.24*time/attack;else if(time<decay)env=.24*(.095/.24)**((time-attack)/(decay-attack));else if(time<duration)env=.095*(.027/.095)**((time-decay)/(duration-decay));else env=.027*(.0001/.027)**((time-duration)/.22);let value=0;for(const [p,a] of [[1,1],[2,.38],[3,.17],[4,.08],[5,.035]])if(hz*p<sr*.45)value+=Math.sin(time*hz*p*2*Math.PI)*a;samples[start+i]+=value*env*velocity*.75;}
  }
  await writeFile(new URL(`${score.id}.wav`,tracksDir),new Uint8Array(encodeWav(samples,sr)));
 }
}
await writeFile(new URL('catalog.json',docs),JSON.stringify({version:1,tracks:catalog},null,2)+'\n');
// Dependency-free PNG app icons. A functional keyboard mark, drawn on a safe inset.
function crc32(data){let c=0xffffffff;for(const b of data){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^(0xedb88320&-(c&1));}return (c^0xffffffff)>>>0;}
function chunk(type,data){const t=Buffer.from(type),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);t.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc32(Buffer.concat([t,data])),8+data.length);return out;}
for(const size of [192,512]){const pixels=Buffer.alloc(size*(1+size*4));for(let y=0;y<size;y++){pixels[y*(size*4+1)]=0;for(let x=0;x<size;x++){const u=x/size*192,v=y/size*192;let c=[23,37,55];if(u>=44&&u<148&&v>=47&&v<145)c=[255,255,255];if(((u>=76&&u<81)||(u>=111&&u<116))&&v>=47&&v<145)c=[23,37,55];if(((u>=68&&u<88)||(u>=103&&u<123))&&v>=47&&v<104)c=[23,37,55];if((u-146)**2+(v-45)**2<15**2)c=[121,158,255];const o=y*(size*4+1)+1+x*4;pixels[o]=c[0];pixels[o+1]=c[1];pixels[o+2]=c[2];pixels[o+3]=255;}}const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(size);ihdr.writeUInt32BE(size,4);ihdr[8]=8;ihdr[9]=6;await writeFile(new URL(`icon-${size}.png`,docs),Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]));}
const assets=['./','./index.html','./styles.css','./main.js','./views.js','./core.js','./score.js','./audio.js','./storage.js','./follower.js','./icons.js','./dialogs.js','./touch-loop.js','./manifest.webmanifest','./icon.svg','./icon-192.png','./icon-512.png','./catalog.json'];
const hash=createHash('sha256');for(const asset of assets.filter(a=>a!=='./'))hash.update(await readFile(new URL(asset,docs)));
const version=hash.digest('hex').slice(0,16);
const sw=`// Generated by scripts/prepare.mjs. App assets only; song data is managed in IndexedDB.\nconst PREFIX='prelude:'+self.registration.scope+':';\nconst CACHE=PREFIX+'${version}';\nconst ASSETS=${JSON.stringify(assets)};\nself.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));\nself.addEventListener('activate',event=>event.waitUntil((async()=>{for(const key of await caches.keys())if(key.startsWith(PREFIX)&&key!==CACHE)await caches.delete(key);await self.clients.claim();})()));\nself.addEventListener('fetch',event=>{const url=new URL(event.request.url),base=new URL(self.registration.scope);if(event.request.method!=='GET'||url.origin!==base.origin||!url.pathname.startsWith(base.pathname))return;const relative=url.pathname.slice(base.pathname.length);if(relative.startsWith('tracks/'))return;event.respondWith((async()=>{const cache=await caches.open(CACHE);if(relative==='catalog.json'){try{const res=await fetch(event.request);if(res.ok)await cache.put(event.request,res.clone());return res;}catch{const cached=await cache.match(event.request);return cached||new Response('Offline',{status:503});}}const cached=await cache.match(event.request,{ignoreSearch:true});if(cached)return cached;if(event.request.mode==='navigate')return await cache.match(new URL('./index.html',base))||fetch(event.request);return fetch(event.request);})());});\n`;
await writeFile(new URL('sw.js',docs),sw);
await writeFile(new URL('.nojekyll',docs),'');
console.log(`Prepared ${catalog.length} tracks, cache ${version}.`);
