// One-time local setup. The browser sends only the encrypted key configuration.
import http from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {validateVault,importPublicKey} from '../docs/crypto.js';
const output=process.argv[2];if(!output)throw Error('Usage: node scripts/setup-vault.mjs <output-directory>');
const dir=path.resolve(output),port=43190,origin=`http://127.0.0.1:${port}`;let complete=false;
const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Prélude パスワード初期設定</title><style>body{font:16px/1.8 system-ui,sans-serif;background:#f3f5fb;color:#172537;margin:0;padding:30px}main{max-width:550px;margin:5vh auto;background:white;border-radius:20px;padding:32px;box-shadow:0 12px 40px #18263b10}h1{font-size:25px}label{display:block;margin:20px 0}input{display:block;box-sizing:border-box;width:100%;padding:14px;font:inherit;border:1px solid #cdd5e1;border-radius:9px}button{font:inherit;background:#365ee8;color:white;padding:14px 22px;border:0;border-radius:10px;width:100%}button:disabled{opacity:.55}.hint{color:#657084;font-size:14px}#status{white-space:pre-wrap}a{color:#365ee8}</style><main><h1>Prélude 共通パスワード</h1><p>iPadやPCで同じ曲を開くためのパスワードを設定します。</p><form id="setup"><label>パスワード（8文字以上・数字だけでも可）<input id="password" type="password" autocomplete="new-password" minlength="8" maxlength="1024" required></label><label>確認のためもう一度<input id="confirmation" type="password" autocomplete="new-password" required></label><p class="hint">長めの、ほかのサービスで使っていないものをおすすめします。パスワードはこの画面の中でのみ処理し、チャット・GitHub・設定用サーバーへ送信しません。忘れないようパスワード管理アプリ等に控えてください。</p><button id="create">このパスワードで設定する</button></form><p id="status" role="status"></p></main><script type="module" src="/setup.js"></script></html>`;
const js=`import {createVault,unlockVault} from '/crypto.js';document.querySelector('#setup').onsubmit=async e=>{e.preventDefault();const p=document.querySelector('#password'),c=document.querySelector('#confirmation'),b=document.querySelector('#create'),s=document.querySelector('#status');if(p.value!==c.value){s.textContent='2つのパスワードが一致しません。';return;}b.disabled=true;s.textContent='安全な鍵を作成しています…';try{const config=await createVault(p.value);await unlockVault(p.value,config);p.value='';c.value='';const response=await fetch('/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});if(!response.ok)throw Error('設定を保存できませんでした。');document.querySelector('#setup').hidden=true;s.textContent='設定が完了しました。チャットに「設定完了」とお知らせください。アプリへの反映を進めます。';}catch(error){s.textContent=error.message;b.disabled=false;}};`;
const server=http.createServer(async(req,res)=>{try{
 if(req.headers.host!==`127.0.0.1:${port}`){res.writeHead(403).end();return;}
 const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'unsafe-inline'; frame-ancestors 'none'; form-action 'none'"};
 if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{...headers,'Content-Type':'text/html; charset=utf-8'}).end(html);return;}
 if(req.method==='GET'&&req.url==='/setup.js'){res.writeHead(200,{...headers,'Content-Type':'text/javascript; charset=utf-8'}).end(js);return;}
 if(req.method==='GET'&&req.url==='/crypto.js'){res.writeHead(200,{...headers,'Content-Type':'text/javascript; charset=utf-8'}).end(await readFile(new URL('../docs/crypto.js',import.meta.url)));return;}
 if(req.method==='POST'&&req.url==='/complete'&&!complete){if(req.headers.origin!==origin||req.headers['content-type']!=='application/json'){res.writeHead(403).end();return;}let raw='';for await(const part of req){raw+=part;if(raw.length>20000){res.writeHead(413).end();return;}}const input=validateVault(JSON.parse(raw));await importPublicKey(input);const config={type:input.type,version:input.version,id:input.id,publicKey:input.publicKey,kdf:{name:input.kdf.name,hash:input.kdf.hash,iterations:input.kdf.iterations,salt:input.kdf.salt},privateKey:{algorithm:input.privateKey.algorithm,iv:input.privateKey.iv,data:input.privateKey.data}};await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'vault.json'),JSON.stringify(config,null,2)+'\n',{flag:'wx'});complete=true;res.writeHead(200,headers).end('Saved');console.log('Encrypted vault configuration saved. Password was not received.');return;}
 res.writeHead(404,headers).end('Not found');
 }catch{res.writeHead(400).end('Invalid setup data');}});
server.listen(port,'127.0.0.1',()=>console.log(`Password setup: ${origin}/`));
